// Code generated by github.com/utgwkk/gosimplectorgen. DO NOT EDIT.

package example

import (
	"github.com/utgwkk/gosimplectorgen/example/bar"
	"github.com/utgwkk/gosimplectorgen/example/baz"
	"github.com/utgwkk/gosimplectorgen/example/foo"
)

func NewPrivateStruct(
	foo foo.Foo,
	bar bar.Bar,
	baz baz.Baz,
) *privateStruct {
	return &privateStruct{
		foo: foo,
		bar: bar,
		baz: baz,
	}
}
