package generator

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io"
	"slices"
	"strings"

	"golang.org/x/tools/go/ast/inspector"
)

type Generator struct {
	w io.Writer

	srcFile string

	targetTypes []string
}

func New(w io.Writer, srcFile string, targetTypes []string) *Generator {
	return &Generator{w: w, srcFile: srcFile, targetTypes: targetTypes}
}

type fieldInfo struct {
	name string
	typ  ast.Expr
}

type structInfo struct {
	name   string
	fields []fieldInfo
}

func (g *Generator) Generate() error {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, g.srcFile, nil, 0)
	if err != nil {
		return fmt.Errorf("parser.ParseFile: %w", err)
	}

	in := inspector.New([]*ast.File{f})
	var structs []structInfo
	for typeSpec := range inspector.All[*ast.TypeSpec](in) {
		structType, ok := typeSpec.Type.(*ast.StructType)
		if !ok {
			continue
		}
		if !g.isTargetType(typeSpec.Name.Name) {
			continue
		}
		var fields []fieldInfo
		for _, field := range structType.Fields.List {
			if len(field.Names) == 0 {
				continue
			}
			for _, name := range field.Names {
				fields = append(fields, fieldInfo{
					name: name.Name,
					typ:  field.Type,
				})
			}
		}
		structs = append(structs, structInfo{
			name:   typeSpec.Name.Name,
			fields: fields,
		})
	}

	var buf bytes.Buffer

	// Emit the "do not edit" header and package declaration.
	fmt.Fprintln(&buf, "// Code generated by github.com/utgwkk/gosimplectorgen. DO NOT EDIT.")
	fmt.Fprintln(&buf)
	fmt.Fprintf(&buf, "package %s\n", f.Name.Name)
	fmt.Fprintln(&buf)

	// Emit an import block containing only the packages actually referenced by
	// the collected struct field types, preserving any alias names from the
	// source file.
	usedPkgs := collectUsedPackages(structs)
	var usedImports []*ast.ImportSpec
	for _, imp := range f.Imports {
		if usedPkgs[importPackageName(imp)] {
			usedImports = append(usedImports, imp)
		}
	}
	if len(usedImports) > 0 {
		fmt.Fprintln(&buf, "import (")
		for _, imp := range usedImports {
			if imp.Name != nil {
				fmt.Fprintf(&buf, "\t%s %s\n", imp.Name.Name, imp.Path.Value)
			} else {
				fmt.Fprintf(&buf, "\t%s\n", imp.Path.Value)
			}
		}
		fmt.Fprintln(&buf, ")")
		fmt.Fprintln(&buf)
	}

	// Emit a constructor function for each collected struct.
	// Each constructor accepts one parameter per exported or unexported field
	// and returns a pointer to the newly allocated struct with all fields set.
	for _, s := range structs {
		// Emit the function signature: "func NewFoo(\n".
		fmt.Fprintf(&buf, "func %s(\n", constructorName(s.name))
		for _, field := range s.fields {
			typeStr, err := exprToString(fset, field.typ)
			if err != nil {
				return fmt.Errorf("print type for %s.%s: %w", s.name, field.name, err)
			}
			// Emit one parameter line per field: "\tfieldName FieldType,\n".
			fmt.Fprintf(&buf, "\t%s %s,\n", field.name, typeStr)
		}
		// Emit the return type and opening brace: ") *Foo {\n".
		fmt.Fprintf(&buf, ") *%s {\n", s.name)
		// Emit the composite literal that initialises every field.
		fmt.Fprintf(&buf, "\treturn &%s{\n", s.name)
		for _, field := range s.fields {
			fmt.Fprintf(&buf, "\t\t%s: %s,\n", field.name, field.name)
		}
		fmt.Fprintln(&buf, "\t}")
		fmt.Fprintln(&buf, "}")
		fmt.Fprintln(&buf)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format.Source: %w\n%s", err, buf.String())
	}
	_, err = g.w.Write(formatted)
	return err
}

func (g *Generator) isTargetType(typename string) bool {
	if len(g.targetTypes) == 0 {
		return true
	}
	return slices.Contains(g.targetTypes, typename)
}

func collectUsedPackages(structs []structInfo) map[string]bool {
	used := make(map[string]bool)
	for _, s := range structs {
		for _, field := range s.fields {
			collectPackagesFromExpr(field.typ, used)
		}
	}
	return used
}

func collectPackagesFromExpr(expr ast.Expr, used map[string]bool) {
	ast.Inspect(expr, func(n ast.Node) bool {
		if sel, ok := n.(*ast.SelectorExpr); ok {
			if ident, ok := sel.X.(*ast.Ident); ok {
				used[ident.Name] = true
			}
		}
		return true
	})
}

func importPackageName(imp *ast.ImportSpec) string {
	if imp.Name != nil {
		return imp.Name.Name
	}
	path := imp.Path.Value[1 : len(imp.Path.Value)-1] // strip quotes
	parts := strings.Split(path, "/")
	return parts[len(parts)-1]
}

func constructorName(typeName string) string {
	return "New" + strings.ToUpper(typeName[:1]) + typeName[1:]
}

func exprToString(fset *token.FileSet, expr ast.Expr) (string, error) {
	var buf bytes.Buffer
	if err := format.Node(&buf, fset, expr); err != nil {
		return "", err
	}
	return buf.String(), nil
}
