package generator

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io"
	"slices"
	"strings"
)

type Generator struct {
	w io.Writer

	srcFile string

	targetTypes []string

	imports []string
}

func New(w io.Writer, srcFile string) *Generator {
	return &Generator{w: w, srcFile: srcFile}
}

type fieldInfo struct {
	name string
	typ  ast.Expr
}

type structInfo struct {
	name   string
	fields []fieldInfo
}

func (g *Generator) Generate() error {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, g.srcFile, nil, 0)
	if err != nil {
		return fmt.Errorf("parser.ParseFile: %w", err)
	}

	var structs []structInfo
	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}
			if !g.isTargetType(typeSpec.Name.Name) {
				continue
			}
			var fields []fieldInfo
			for _, field := range structType.Fields.List {
				if len(field.Names) == 0 {
					continue
				}
				for _, name := range field.Names {
					fields = append(fields, fieldInfo{
						name: name.Name,
						typ:  field.Type,
					})
				}
			}
			structs = append(structs, structInfo{
				name:   typeSpec.Name.Name,
				fields: fields,
			})
		}
	}

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "// Code generated by github.com/utgwkk/gosimplectorgen. DO NOT EDIT.")
	fmt.Fprintln(&buf)
	fmt.Fprintf(&buf, "package %s\n", f.Name.Name)
	fmt.Fprintln(&buf)

	if len(f.Imports) > 0 {
		fmt.Fprintln(&buf, "import (")
		for _, imp := range f.Imports {
			if imp.Name != nil {
				fmt.Fprintf(&buf, "\t%s %s\n", imp.Name.Name, imp.Path.Value)
			} else {
				fmt.Fprintf(&buf, "\t%s\n", imp.Path.Value)
			}
		}
		fmt.Fprintln(&buf, ")")
		fmt.Fprintln(&buf)
	}

	for _, s := range structs {
		fmt.Fprintf(&buf, "func %s(\n", constructorName(s.name))
		for _, field := range s.fields {
			typeStr, err := exprToString(fset, field.typ)
			if err != nil {
				return fmt.Errorf("print type for %s.%s: %w", s.name, field.name, err)
			}
			fmt.Fprintf(&buf, "\t%s %s,\n", field.name, typeStr)
		}
		fmt.Fprintf(&buf, ") *%s {\n", s.name)
		fmt.Fprintf(&buf, "\treturn &%s{\n", s.name)
		for _, field := range s.fields {
			fmt.Fprintf(&buf, "\t\t%s: %s,\n", field.name, field.name)
		}
		fmt.Fprintln(&buf, "\t}")
		fmt.Fprintln(&buf, "}")
		fmt.Fprintln(&buf)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format.Source: %w\n%s", err, buf.String())
	}
	_, err = g.w.Write(formatted)
	return err
}

func (g *Generator) isTargetType(typename string) bool {
	if len(g.targetTypes) == 0 {
		return true
	}
	return slices.Contains(g.targetTypes, typename)
}

func constructorName(typeName string) string {
	return "New" + strings.ToUpper(typeName[:1]) + typeName[1:]
}

func exprToString(fset *token.FileSet, expr ast.Expr) (string, error) {
	var buf bytes.Buffer
	if err := format.Node(&buf, fset, expr); err != nil {
		return "", err
	}
	return buf.String(), nil
}
