package generator

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io"
	"os"
	"slices"
	"strconv"
	"strings"

	"golang.org/x/tools/go/ast/inspector"
	"golang.org/x/tools/imports"
)

type Generator struct {
	w io.Writer

	srcFile string

	targetTypes []string
}

func New(w io.Writer, srcFile string, targetTypes []string) *Generator {
	return &Generator{w: w, srcFile: srcFile, targetTypes: targetTypes}
}

type fieldInfo struct {
	name string
	typ  ast.Expr
}

type structInfo struct {
	name   string
	fields []fieldInfo
}

func (g *Generator) Generate() error {
	src, err := os.ReadFile(g.srcFile)
	if err != nil {
		return fmt.Errorf("os.ReadFile: %w", err)
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, g.srcFile, src, 0)
	if err != nil {
		return fmt.Errorf("parser.ParseFile: %w", err)
	}

	structs := g.collectStructInfo(f)

	var buf bytes.Buffer

	// Emit the "do not edit" header and package declaration.
	buf.WriteString("// Code generated by github.com/utgwkk/gosimplectorgen. DO NOT EDIT.\n")
	buf.WriteString("\n")
	buf.WriteString("package ")
	buf.WriteString(f.Name.Name)
	buf.WriteString("\n")
	buf.WriteString("\n")

	// Emit an import block containing only the packages actually referenced by
	// the collected struct field types, preserving any alias names from the
	// source file.
	usedPkgs := collectUsedPackages(structs)
	var usedImports []*ast.ImportSpec
	for _, imp := range f.Imports {
		if usedPkgs[importPackageName(imp)] {
			usedImports = append(usedImports, imp)
		}
	}
	if len(usedImports) > 0 {
		buf.WriteString("import (\n")
		for _, imp := range usedImports {
			if imp.Name != nil {
				buf.WriteString("\t")
				buf.WriteString(imp.Name.Name)
				buf.WriteString(" ")
				buf.WriteString(imp.Path.Value)
				buf.WriteString("\n")
			} else {
				buf.WriteString("\t")
				buf.WriteString(imp.Path.Value)
				buf.WriteString("\n")
			}
		}
		buf.WriteString(")\n")
		buf.WriteString("\n")
	}

	// Emit a constructor function for each collected struct.
	// Each constructor accepts one parameter per exported or unexported field
	// and returns a pointer to the newly allocated struct with all fields set.
	for _, s := range structs {
		// Emit the function signature: "func NewFoo(\n".
		buf.WriteString("func ")
		buf.WriteString(constructorName(s.name))
		buf.WriteString("(\n")
		for _, field := range s.fields {
			// Extract the type string by slicing the source bytes directly,
			// avoiding the allocation cost of go/printer + tabwriter per field.
			// imports.Process at the end normalises any whitespace irregularities.
			start := fset.Position(field.typ.Pos()).Offset
			end := fset.Position(field.typ.End()).Offset
			typeStr := string(src[start:end])
			// Emit one parameter line per field: "\tfieldName FieldType,\n".
			buf.WriteString("\t")
			buf.WriteString(field.name)
			buf.WriteString(" ")
			buf.WriteString(typeStr)
			buf.WriteString(",\n")
		}
		// Emit the return type and opening brace: ") *Foo {\n".
		buf.WriteString(") *")
		buf.WriteString(s.name)
		buf.WriteString(" {\n")
		// Emit the composite literal that initialises every field.
		buf.WriteString("\treturn &")
		buf.WriteString(s.name)
		buf.WriteString("{\n")
		for _, field := range s.fields {
			buf.WriteString("\t\t")
			buf.WriteString(field.name)
			buf.WriteString(": ")
			buf.WriteString(field.name)
			buf.WriteString(",\n")
		}
		buf.WriteString("\t}\n")
		buf.WriteString("}\n")
		buf.WriteString("\n")
	}

	formatted, err := imports.Process("", buf.Bytes(), nil)
	if err != nil {
		return fmt.Errorf("imports.Process: %w\n%s", err, buf.String())
	}
	_, err = g.w.Write(formatted)
	return err
}

func (g *Generator) collectStructInfo(f *ast.File) []structInfo {
	var structs []structInfo
	in := inspector.New([]*ast.File{f})
	for typeSpec := range inspector.All[*ast.TypeSpec](in) {
		structType, ok := typeSpec.Type.(*ast.StructType)
		if !ok {
			continue
		}
		if !g.isTargetType(typeSpec.Name.Name) {
			continue
		}
		var fields []fieldInfo
		for _, field := range structType.Fields.List {
			if len(field.Names) == 0 {
				continue
			}
			for _, name := range field.Names {
				fields = append(fields, fieldInfo{
					name: name.Name,
					typ:  field.Type,
				})
			}
		}
		structs = append(structs, structInfo{
			name:   typeSpec.Name.Name,
			fields: fields,
		})
	}
	return structs
}

func (g *Generator) isTargetType(typename string) bool {
	if len(g.targetTypes) == 0 {
		return true
	}
	return slices.Contains(g.targetTypes, typename)
}

func collectUsedPackages(structs []structInfo) map[string]bool {
	used := make(map[string]bool)
	for _, s := range structs {
		for _, field := range s.fields {
			collectPackagesFromExpr(field.typ, used)
		}
	}
	return used
}

func collectPackagesFromExpr(expr ast.Expr, used map[string]bool) {
	ast.Inspect(expr, func(n ast.Node) bool {
		if sel, ok := n.(*ast.SelectorExpr); ok {
			if ident, ok := sel.X.(*ast.Ident); ok {
				used[ident.Name] = true
			}
		}
		return true
	})
}

func importPackageName(imp *ast.ImportSpec) string {
	if imp.Name != nil {
		return imp.Name.Name
	}
	// NOTE: imp.Path.Value is always quoted
	path, _ := strconv.Unquote(imp.Path.Value)
	pkgName := path[strings.LastIndex(path, "/")+1:]
	return pkgName
}

func constructorName(typeName string) string {
	return "New" + strings.ToUpper(typeName[:1]) + typeName[1:]
}
